### ISSUE TITLE
secretflow.stats.biclassification_eval.BiClassificationEval函数怎么计算Precision, Recall的结果

### ISSUE THREAD

**Issue by kitesssss** [secretflow/secretflow#434]
from secretflow.stats.biclassification_eval import BiClassificationEval

biclassification_evaluator = BiClassificationEval(
    y_true=test_y, y_score=lr_y_hat, bucket_size=20
)
lr_report = sf.reveal(biclassification_evaluator.get_all_reports())
print(f'positive_samples: {lr_report.summary_report.positive_samples}')
print(f'negative_samples: {lr_report.summary_report.negative_samples}')
print(f'total_samples: {lr_report.summary_report.total_samples}')
print(f'f1_score: {lr_report.summary_report.f1_score}')
print(f'auc: {lr_report.summary_report.auc}')
BiClassificationEval好像没有直接求Precision, Recall的函数

**Comment by da-niao-dan** [comment]
Precision and Recall depends on what threshold you take. See
```
class Report:
    """Report containing all other reports for bi-classification evaluation

    Attributes:
        summary_report: SummaryReport

        group_reports: List[GroupReport]

        eq_frequent_bin_report: List[EqBinReport]

        eq_range_bin_report: List[EqBinReport]

        head_report: List[PrReport]
            reports for fpr = 0.001, 0.005, 0.01, 0.05, 0.1, 0.2
    """
```

find precision and recall in eq_frequent_bin_report, eq_range_bin_report or head_report
